### ISSUE TITLE
alt-S is not working

### ISSUE THREAD

**Issue by MooersLab** [tommyshem/micro-snippets-plugin#1]
I am using a Mac OS X 10.14.
I installed the snippets plugin.
When I enter alt-s, I get a lowercase beta inserted into my text. 

I appreciate the other snippet commands. 
These are more than are  available in other text editors. 

By the way, coming from other text editors, 
I except to use a tab after typing a tab trigger name to insert a snippet. 

To mimic that behavior, I tried define a new keybinding in the file ~/.config/micro/bindings.json

"Tab,":              "SnippetInsert",

This failed because SnippetInsert is not recognized.

**Comment by tommyshem** [comment]
@MooersLab 
Try below for binding the tab key to the snippet insert function in file `~/.config/micro/bindings.json`
```json
{
"Tab": "snippets.Insert"
}
```

I will look into the key bindings on Mac OS X when I have time this weekend.

Hope this helps you.

**Comment by MooersLab** [comment]
@tommyshem
I did as suggested. 
Now I get a message that my snippet is not found. 
I have insert my pml.snippets file below.
I replaced the spaces with tabs, but that still did not solve the problem. 

![Screen Shot 2019-10-12 at 10 18 12 AM](https://user-images.githubusercontent.com/15176203/66703913-0eb23b80-ecdd-11e9-8d49-4ebf20f6acf2.png)

```bash
# PyMOL snippets
# Ambiant occlussion
snippet ao
	set_color oxygen, [1.0,0.4,0.4];
	set_color nitrogen, [0.5,0.5,1.0];
	remove solvent;
	as spheres;
	util.cbaw;
	bg white;
	set light_count,10;
	set spec_count,1;
	set shininess, 10;
	set specular,0.25;
	set ambient,0;
	set direct,0;
	set reflect,1.5;
	set ray_shadow_decay_factor, 0.1;
	set ray_shadow_decay_range, 2;
	unset depth_cue;
	ray;
	$0
```

Here is the test.pml file:

```python
fetch 1lw9
show spheres
```

**Comment by tommyshem** [comment]
@MooersLab 
Where have you saved the snippet file ?

The snippets plugin only looks in the plugin snippets folder.
The snippet filename has to match the file type on the micro editor and not the file extension eg.
The image you shown above shows file type `pymol` so the snippet filename has to be `pymol.snippets` in the plugin snippets folder.

`~/.config/micro/plugins/snippets/snippets/pymol.snippets`

For more info about what is happening with the snippet plugin.
In micro editor press `control` +  `e`  to go in to commad mode and type `log`

It should show another window with error logs and info.

Hope this helps you.

**Comment by tommyshem** [comment]
I have put the macOS instructions on how to get the left `alt` key working for micro editor, in the README.md file now. As by default the `Alt` key bindings do not work in micro editor, so the key bindings for this plugin does not work, without changing the settings in the terminal.
