### ISSUE TITLE
Please document with usage examples

### ISSUE THREAD

**Issue by iio7** [tommyshem/micro-snippets-plugin#4]
Is it supposed to be obvious how this plugin is used?

**Comment by tommyshem** [comment]
Most plugins come with a help file.

In Micro editor press `ctrl e` for the command mode and type `help snippets`

You can see the help files for other plugins, by using the same method but changing the name after the help command.

To see help files available you can type `help `and TAB key to see the available help files.

Basic usage type part of the key word and press 'Alt-s' if the keyword is in the snippets file, then it will put the snippet text in the editor. 

The same help file from with in micro editor but on githib https://github.com/tommyshem/micro-snippets-plugin/blob/master/help/snippets.md
